src/DnD/Controllers/AdventureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DnD.Data;
using DnD.Models;
using DnD.Models.AdventureViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using DnD.Services;

namespace DnD.Controllers
{
    [Authorize]
    public class AdventureController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly AdventureManager manager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdventureController(ApplicationDbContext context, AdventureManager manager, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.manager = manager;
            this.userManager = userManager;
        }

        private Adventure AdventureFromViewModel(AdventureViewModel viewModel, Adventure adventure = null)
        {
            if(adventure == null) { adventure = new Adventure(); }
            adventure.Name = viewModel.Name;
            adventure.Description = viewModel.Description;
            adventure.Date = viewModel.Date ?? DateTime.Today; //TODO: Make Adventure.Date optional
            adventure.DungeonMasterId = viewModel.DungeonMasterId;
            adventure.PreviousId = viewModel.PreviousId;
            adventure.NextId = viewModel.NextId;
            return adventure;
        }

        private void PrepareFormViewData(string dungeonMasterId, int? previousId = null, int? nextId = null)
        {
            ViewData["DungeonMasters"] = new SelectList(context.Users.OrderBy(u => u.DisplayName), nameof(ApplicationUser.Id), nameof(ApplicationUser.DisplayName), dungeonMasterId);
            var adventures = context.Adventures
                .OrderByDescending(a => a.Date)
                .Select(a => new { Id = a.Id, Name = $"{a.Name} ({a.Date:d})" });
            ViewData["Previous"] = new SelectList(adventures, "Id", "Name", previousId);
            ViewData["Next"] = new SelectList(adventures, "Id", "Name", nextId);
        }

        private void PrepareAdventurersViewData(int adventureId, IEnumerable<int> selected = null)
        {
            var characters = context.Characters
                .Where(c => !c.Adventures.Any(ap => ap.AdventureId == adventureId))
                .OrderBy(c => c.Name);
            ViewData["Characters"] = new MultiSelectList(characters, nameof(Character.Id), nameof(Character.Name), selected);
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = context.Adventures
                .Include(a => a.DungeonMaster)
                .OrderByDescending(a => a.Date);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) { return NotFound(); }
            var adventure = await context.Adventures
                .Include(a => a.DungeonMaster)
                .Include(a => a.Previous)
                .Include(a => a.Next)
                .Include(a => a.Adventurers)
                    .ThenInclude(ap => ap.Adventurer)
                    .ThenInclude(c => c.Race)
                .Include(a => a.Adventurers)
                    .ThenInclude(ap => ap.GoldLoot)
                .Include(a => a.Adventurers)
                    .ThenInclude(ap => ap.ExperienceLoot)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (adventure == null) { return NotFound(); }
            PrepareAdventurersViewData(id.Value);

            return View(adventure);
        }

        public async Task<IActionResult> Create()
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            PrepareFormViewData(user.Id);
            return View();
        }

        // POST: Adventure/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Date,Description,DungeonMasterId,Name,NextId,PreviousId")] AdventureViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var newAdventure = AdventureFromViewModel(viewModel);
                await manager.CreateAsync(newAdventure);
                return RedirectToAction("Details", new { Id = newAdventure.Id });
            }
            PrepareFormViewData(viewModel.DungeonMasterId, viewModel.PreviousId, viewModel.NextId);
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) { return NotFound(); }
            var adventure = await context.Adventures.SingleOrDefaultAsync(m => m.Id == id);
            if (adventure == null) { return NotFound(); }

            PrepareFormViewData(adventure.DungeonMasterId, adventure.PreviousId, adventure.NextId);
            return View(new AdventureViewModel()
            {
                Id = adventure.Id,
                Name = adventure.Name,
                Date = adventure.Date,
                DungeonMasterId = adventure.DungeonMasterId,
                Description = adventure.Description,
                PreviousId = adventure.PreviousId,
                NextId = adventure.NextId
            });
        }

        // POST: Adventure/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Description,DungeonMasterId,Name,NextId,PreviousId")] AdventureViewModel viewModel)
        {
            if (!viewModel.Id.HasValue || id != viewModel.Id.Value) { return NotFound(); }

            if (ModelState.IsValid)
            {
                try
                {
                    await manager.UpdateAsync(AdventureFromViewModel(viewModel, await context.Adventures.SingleAsync(a => a.Id == id)));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdventureExists(id)) { return NotFound(); }
                    else { throw; }
                }
                return RedirectToAction("Details", new { Id = id });
            }

            PrepareFormViewData(viewModel.DungeonMasterId, viewModel.PreviousId, viewModel.NextId);
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) { return NotFound(); }
            var adventure = await context.Adventures
                .Include(a => a.DungeonMaster)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (adventure == null) { return NotFound(); }

            return View(adventure);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adventure = await context.Adventures.SingleOrDefaultAsync(m => m.Id == id);
            context.Adventures.Remove(adventure);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAdventurers(AddAdventurersViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await manager.AddAdventurers(viewModel.AdventureId, viewModel.Adventurers);
                return RedirectToAction("Details", new { Id = viewModel.AdventureId });
            }
            PrepareAdventurersViewData(viewModel.AdventureId, viewModel.Adventurers);
            ViewData["Adventures"] = new SelectList(context.Adventures.OrderByDescending(a => a.Date), nameof(Adventure.Id), nameof(Adventure.Name), viewModel.AdventureId);
            return View(viewModel);
        }

        private bool AdventureExists(int id)
        {
            return context.Adventures.Any(e => e.Id == id);
        }
    }
}

src/DnD/Views/Shared/_CharacterCardHeader.cshtml
@model DnD.Models.Character

<div class="content no-grow">
    <div class="right floated meta">@Html.DisplayFor(model => model.Race.Name)</div>
    <div class="header">
        <a asp-action="Details" asp-controller="Character" asp-route-id="@Model.Id">@Html.DisplayFor(model => model.Name)</a>
        <span data-tooltip="@Html.DisplayFor(model => model.Gender)"><i class="@Html.GenderIcon(Model.Gender) icon"></i></span>
    </div>
    <div class="meta">@Html.DisplayFor(model => model.Owner.DisplayName)</div>
</div>

src/DnD/Views/Shared/_FormErrorSummary.cshtml
<div class="ui warning icon message validation-summary">
    <i class="warning circle icon"></i>
    <div class="content">
        <div class="header">Errors</div>
        <div asp-validation-summary="All" class="summary-content"></div>
    </div>
</div>

src/DnD/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DnD</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/semantic/dist/semantic.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui-calendar/dist/calendar.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/semantic/dist/semantic.min.css" />
        <link rel="stylesheet" href="~/lib/semantic-ui-calendar/dist/calendar.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="ui top green stackable menu">
        <a asp-area="" asp-controller="Home" asp-action="Index" class="@Html.IsActiveAction("Index", "Home") header item"><i class="home icon"></i> Home</a>
        <a asp-area="" asp-controller="Home" asp-action="About" class="@Html.IsActiveAction("About", "Home") item"><i class="info icon"></i> About</a>
        @if (SignInManager.IsSignedIn(User))
        {
            <a asp-area="" asp-controller="Character" asp-action="Index" class="@Html.IsActiveAction(controllers: "Character") item"><i class="@Html.CharacterIcon() icon"></i> Characters</a>
            <a asp-area="" asp-controller="Adventure" asp-action="Index" class="@Html.IsActiveAction(controllers: "Adventure") item"><i class="map icon"></i> Adventures</a>
        }
        @await Html.PartialAsync("_LoginPartial")
    </div>
    <div id="content" class="ui container">
        <h1>@ViewData["Title"]</h1>
        @RenderBody()
        <div style="height: 100px"></div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/semantic/dist/semantic.js"></script>
        <script src="~/lib/semantic-ui-calendar/dist/calendar.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/semantic/dist/semantic.min.js"></script>
        <script src="~/lib/semantic-ui-calendar/dist/calendar.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>