src/DnD/Models/Character.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DnD.Models
{
    public class Character
    {
        /// <summary>InitialLife + InitialMana has to be equal to this number. (Except for dragons, that start with predefined stats.)</summary>
        public const int InitialLifePlusMana = 15;

        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Gender { get; set; }

        [Required]
        public int InitialLife { get; set; }

        [Required]
        public int InitialMana { get; set; }

        public string OwnerId { get; set; }
        [Required]
        public ApplicationUser Owner { get; set; }

        public int RaceId { get; set; }
        [Required]
        public Race Race { get; set; }

        [InverseProperty("Adventurer")]
        public List<AdventureParticipation> Adventures { get; set; }

        [InverseProperty("Character")]
        public List<Gold> Gold { get; set; }

        [InverseProperty("Character")]
        public List<Experience> Experience { get; set; }
    }
}

src/DnD/Models/CharacterViewModels/AddExperienceViewModel.cs
using DnD.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DnD.Models.CharacterViewModels
{
    public class AddExperienceViewModel : IValidatableObject
    {
        [Display(Name = "Adventure")]
        public int? AdventureId { get; set; }

        [Display(Name = "Character")]
        public int AdventurerId { get; set; }

        public int Amount { get; set; }

        [MaxLength(255)]
        public string Description { get; set; }

        /// <summary>Determines, if the add experience was issued from the adventure or character view.</summary>
        /// <remarks>Possible values are e.g. Adventure or Character</remarks>
        [MaxLength(255)]
        public string From { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Amount <= 0)
            {
                yield return new ValidationResult("Please enter a positive amount", new[] { nameof(Amount) });
            }

            var context = (ApplicationDbContext)validationContext.GetService(typeof(ApplicationDbContext));
            if (AdventureId.HasValue && !context.Adventures.Any(a => a.Id == AdventureId.Value))
            {
                yield return new ValidationResult("An unkown adventure was selected", new[] { nameof(AdventureId) });
            }

            if (!context.Characters.Any(c => c.Id == AdventurerId))
            {
                yield return new ValidationResult("An unkown character was selected", new[] { nameof(AdventurerId) });
            }

            if (AdventureId.HasValue && !context.AdventureParticipations.Any(ap => ap.AdventurerId == AdventurerId && ap.AdventureId == AdventureId.Value))
            {
                yield return new ValidationResult("The selected character does not take part in the selected adventure", new[] { nameof(AdventureId), nameof(AdventurerId) });
            }
        }
    }
}

src/DnD/Models/CharacterViewModels/AddGoldViewModel.cs
using DnD.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DnD.Models.CharacterViewModels
{
    public class AddGoldViewModel : IValidatableObject
    {
        [Display(Name = "Adventure")]
        public int? AdventureId { get; set; }

        [Display(Name = "Character")]
        public int AdventurerId { get; set; }

        public int Amount { get; set; }

        [MaxLength(255)]
        public string Description { get; set; }

        /// <summary>Determines, if the add gold was issued from the adventure or character view.</summary>
        /// <remarks>Possible values are e.g. Adventure or Character</remarks>
        [MaxLength(255)]
        public string From { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if(Amount == 0)
            {
                yield return new ValidationResult("Please select an amount", new[] { nameof(Amount) });
            }

            var context = (ApplicationDbContext)validationContext.GetService(typeof(ApplicationDbContext));
            if (AdventureId.HasValue && !context.Adventures.Any(a => a.Id == AdventureId.Value))
            {
                yield return new ValidationResult("An unkown adventure was selected", new[] { nameof(AdventureId) });
            }

            if (!context.Characters.Any(c => c.Id == AdventurerId))
            {
                yield return new ValidationResult("An unkown character was selected", new[] { nameof(AdventurerId) });
            }
            else if (Amount + context.Gold.Where(g => g.CharacterId == AdventurerId).Sum(g => g.Value) < 0)
            {
                yield return new ValidationResult("This change would lead to a negative gold balance and is therefore not allowed", new[] { nameof(Amount) });
            }

            if(AdventureId.HasValue && !context.AdventureParticipations.Any(ap => ap.AdventurerId == AdventurerId && ap.AdventureId == AdventureId.Value))
            {
                yield return new ValidationResult("The selected character does not take part in the selected adventure", new[] { nameof(AdventureId), nameof(AdventurerId) });
            }
        }
    }
}

src/DnD/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DnD.Data;
using DnD.Models;
using DnD.Models.CharacterViewModels;
using DnD.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace DnD.Controllers
{
    [Authorize]
    public class CharacterController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly CharacterManager manager;
        private readonly UserManager<ApplicationUser> userManager;

        public CharacterController(ApplicationDbContext context, CharacterManager manager, UserManager<ApplicationUser> userManager)
        {
            this.context = context;
            this.manager = manager;
            this.userManager = userManager;
        }

        private async Task<Character> CharacterFromViewModel(CharacterViewModel viewModel, Character character = null)
        {
            if (character == null) { character = new Character(); }
            character.Name = viewModel.Name;
            character.Gender = viewModel.Gender;
            character.RaceId = viewModel.RaceId;
            character.Owner = await userManager.GetUserAsync(User);
            character.InitialLife = viewModel.InitialLife;
            character.InitialMana = viewModel.InitialMana;
            return character;
        }

        private IActionResult RedirectToAdventureOrCharacter(string from, int? adventureId, int adventurerId)
        {
            var viewAdventure = from == "Adventure" && adventureId.HasValue;
            return RedirectToAction
            (
                "Details", viewAdventure ? "Adventure" : "Character",
                new { Id = (viewAdventure ? adventureId.Value : adventurerId) }
            );
        }

        private void PrepareRaceViewData(int raceId) =>
            ViewData["RaceItems"] = new SelectList(context.Races.OrderBy(r => r.Name), nameof(Race.Id), nameof(Race.Name), raceId);

        private void PrepareLootViewData(int? adventureId, int adventurerId)
        {
            ViewData["Adventures"] = new SelectList(context.Adventures.OrderByDescending(a => a.Date), "Id", "DisplayName", adventureId);
            ViewData["Adventurers"] = new SelectList(context.Characters.OrderBy(c => c.Name), nameof(Adventure.Id), nameof(Adventure.Name), adventurerId);
        }

        public async Task<IActionResult> Index()
        {
            var applicationDbContext = context.Characters
                .Include(c => c.Owner)
                .Include(c => c.Race);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) { return NotFound(); }
            var character = await context.Characters
                .Include(c => c.Owner)
                .Include(c => c.Race)
                .Include(c => c.Gold)
                .Include(c => c.Experience)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (character == null) { return NotFound(); }

            return View(character);
        }

        public IActionResult Create()
        {
            ViewData["RaceItems"] = new SelectList(context.Races.OrderBy(r => r.Name), nameof(Race.Id), nameof(Race.Name));
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CharacterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var newCharacter = await CharacterFromViewModel(viewModel);
                await manager.CreateAsync(newCharacter);
                return RedirectToAction("Details", new { Id = newCharacter.Id });
            }

            PrepareRaceViewData(viewModel.RaceId);
            return View(viewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) { return NotFound(); }
            var character = await context.Characters.SingleOrDefaultAsync(m => m.Id == id);
            if (character == null) { return NotFound(); }

            PrepareRaceViewData(character.RaceId);
            return View(new CharacterViewModel()
            {
                Id = character.Id,
                Gender = character.Gender,
                Name = character.Name,
                RaceId = character.RaceId,
                InitialLife = character.InitialLife,
                InitialMana = character.InitialMana
            });
        }

        // POST: Character/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CharacterViewModel viewModel)
        {
            if (!viewModel.Id.HasValue || id != viewModel.Id.Value) { return NotFound(); }

            if (ModelState.IsValid)
            {
                try
                {
                    await manager.UpdateAsync(await CharacterFromViewModel(viewModel, await context.Characters.SingleAsync(c => c.Id == id)));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterExists(id)) { return NotFound(); }
                    else { throw; }
                }
                return RedirectToAction("Details", new { Id = id });
            }

            PrepareRaceViewData(viewModel.RaceId);
            return View(viewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) { return NotFound(); }
            var character = await context.Characters
                .Include(c => c.Race)
                .Include(c => c.Owner)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (character == null) { return NotFound(); }

            return View(character);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var character = await context.Characters.SingleOrDefaultAsync(m => m.Id == id);
            context.Characters.Remove(character);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddGold(AddGoldViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                //Prepare new Gold entity
                var newGold = new Gold()
                {
                    Value = viewModel.Amount,
                    Description = viewModel.Description,
                    CharacterId = viewModel.AdventurerId
                };
                if (viewModel.AdventureId.HasValue)
                {
                    var participation = await context.AdventureParticipations
                        .SingleAsync(ap => ap.AdventureId == viewModel.AdventureId && ap.AdventurerId == viewModel.AdventurerId);
                    newGold.LootFromId = participation.Id;
                }

                //Add Gold to database
                await manager.AddGoldAsync(newGold);

                //Redirect back to character or adventure
                return RedirectToAdventureOrCharacter(viewModel.From, viewModel.AdventureId, viewModel.AdventurerId);
            }

            PrepareLootViewData(viewModel.AdventureId, viewModel.AdventurerId);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddExperience(AddExperienceViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                //Prepare new Experience entity
                var newExperience = new Experience()
                {
                    Value = viewModel.Amount,
                    Description = viewModel.Description,
                    CharacterId = viewModel.AdventurerId
                };
                if (viewModel.AdventureId.HasValue)
                {
                    var participation = await context.AdventureParticipations
                        .SingleAsync(ap => ap.AdventureId == viewModel.AdventureId && ap.AdventurerId == viewModel.AdventurerId);
                    newExperience.LootFromId = participation.Id;
                }

                //Add Gold to database
                await manager.AddExperienceAsync(newExperience);

                //Redirect back to character or adventure
                return RedirectToAdventureOrCharacter(viewModel.From, viewModel.AdventureId, viewModel.AdventurerId);
            }

            PrepareLootViewData(viewModel.AdventureId, viewModel.AdventurerId);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveGold(int id, string from)
        {
            var gold = await context.Gold.Include(g => g.LootFrom).SingleOrDefaultAsync(g => g.Id == id);
            if(gold == null) { return NotFound(); }
            var result = RedirectToAdventureOrCharacter(from, gold.LootFrom == null ? null : (int?)gold.LootFrom.AdventureId, gold.CharacterId);

            context.Remove(gold);
            await context.SaveChangesAsync();
            return result;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveExperience(int id, string from)
        {
            var experience = await context.Experience.Include(e => e.LootFrom).SingleOrDefaultAsync(e => e.Id == id);
            if (experience == null) { return NotFound(); }

src/DnD/Controllers/InfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DnD.Data;
using Microsoft.EntityFrameworkCore;

namespace DnD.Controllers
{
    public class InfoController : Controller
    {
        private ApplicationDbContext context;

        public InfoController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var model = context.Races
                .Include(r => r.Attributes)
                .ThenInclude(a => a.Attribute)
                .OrderBy(r => r.Name)
                .ToList();
            return View(model);
        }
    }
}

src/DnD/Views/Character/AddExperience.cshtml
@model AddExperienceViewModel

@{
    ViewData["Title"] = "Add Experience";
}

<form class="ui form summary" asp-action="AddExperience">
    @await Html.PartialAsync("_FormErrorSummary")
    <input type="hidden" asp-for="From" />
    <div class="field">
        <label>
            @Html.DisplayNameFor(a => a.AdventureId)
            <a class="ui tiny red label dropdown-reset" data-tooltip="clear drop down"><i class="remove icon"></i>clear</a>
        </label>
        <select asp-for="AdventureId" asp-items="ViewBag.Adventures" class="ui selection search dropdown create-default"></select>
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="AdventureId"></span>
        </div>
    </div>
    <div class="field">
        <label asp-for="AdventurerId"></label>
        <select asp-for="AdventurerId" asp-items="ViewBag.Adventurers" class="ui selection search dropdown create-default"></select>
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="AdventurerId"></span>
        </div>
    </div>
    <div class="field" data-tooltip="How much gold this adventurer earned or lost">
        <label asp-for="Amount"></label>
        <input asp-for="Amount" placeholder="Amount" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="Amount"></span>
        </div>
    </div>
    <div class="field" data-tooltip="Optional Description">
        <label asp-for="Description"></label>
        <input asp-for="Description" placeholder="Description" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="Description"></span>
        </div>
    </div>
    <button class="ui purple icon labeled button"><i class="lab icon"></i> Add Experience</button>
</form>

src/DnD/Views/Character/AddGold.cshtml
@model AddGoldViewModel

@{
    ViewData["Title"] = "Add Gold";
}

<form class="ui form summary" asp-action="AddGold">
    @await Html.PartialAsync("_FormErrorSummary")
    <input type="hidden" asp-for="From" />
    <div class="field">
        <label>
            @Html.DisplayNameFor(a => a.AdventureId)
            <a class="ui tiny red label dropdown-reset" data-tooltip="clear drop down"><i class="remove icon"></i>clear</a>
        </label>
        <select asp-for="AdventureId" asp-items="ViewBag.Adventures" class="ui selection search dropdown create-default"></select>
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="AdventureId"></span>
        </div>
    </div>
    <div class="field">
        <label asp-for="AdventurerId"></label>
        <select asp-for="AdventurerId" asp-items="ViewBag.Adventurers" class="ui selection search dropdown create-default"></select>
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="AdventurerId"></span>
        </div>
    </div>
    <div class="field" data-tooltip="How much gold this adventurer earned or lost">
        <label asp-for="Amount"></label>
        <input asp-for="Amount" placeholder="Amount" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="Amount"></span>
        </div>
    </div>
    <div class="field" data-tooltip="Optional Description">
        <label asp-for="Description"></label>
        <input asp-for="Description" placeholder="Description" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="Description"></span>
        </div>
    </div>
    <button class="ui yellow icon labeled button" data-tooltip="Add Gold"><i class="cubes icon"></i> Add Gold</button>
</form>

src/DnD/Views/Character/Create.cshtml
@model DnD.Models.CharacterViewModels.CharacterViewModel

@{
    ViewData["Title"] = "Create Character";
}

@await Html.PartialAsync("_Form", Model, new ViewDataDictionary(ViewData) { ["Button"] = "Create", ["Icon"] = "add" })

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <environment names="Development">
        <script src="~/js/characterform.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/characterform.min.js" asp-append-version="true"></script>
    </environment>
}

src/DnD/Views/Character/Delete.cshtml
@model DnD.Models.Character

@{
    ViewData["Title"] = "Delete Character";
}

<h3>Are you sure you want to delete this character?</h3>

@await Html.PartialAsync("_CharacterCard", Model, new ViewDataDictionary(ViewData) { ["HideActions"] = true })

<form asp-action="Delete">
    <button type="submit" class="ui red button"><i class="delete icon"></i>Delete</button>
    <a asp-action="Index">Back to List</a>
</form>

src/DnD/Views/Character/Details.cshtml
@model DnD.Models.Character

@{
    ViewData["Title"] = "Character Details";
}

<section class="ui raised segments">
    <div class="ui segment">
        <span class="ui green ribbon label"><i class="info icon"></i> Info</span>
        <p></p>
        <div class="ui large horizontal divided list">
            <div class="item">
                <div class="content" data-tooltip="Name of this character"><h2>@Html.DisplayFor(model => model.Name)</h2></div>
            </div>
            <div class="item">
                <div class="header">@Html.DisplayNameFor(model => model.Owner)</div>
                <div class="content">@Html.DisplayFor(model => model.Owner.DisplayName)</div>
            </div>
            <div class="item">
                <div class="header">@Html.DisplayNameFor(model => model.Race)</div>
                <div class="content">@Html.DisplayFor(model => model.Race.Name)</div>
            </div>
            <div class="item">
                <div class="header">@Html.DisplayNameFor(model => model.Gender)</div>
                <div class="content">@Html.DisplayFor(model => model.Gender) <i class="@Html.GenderIcon(Model.Gender) icon"></i></div>
            </div>
            <div class="item">
                <div class="header">@Html.DisplayNameFor(model => model.Gold)</div>
                <div class="content"><i class="yellow cubes icon"></i> @Model.Gold.Sum(g => g.Value)</div>
            </div>
            <div class="item">
                <div class="header">@Html.DisplayNameFor(model => model.Experience)</div>
                <div class="content"><i class="purple lab icon"></i> @Model.Experience.Sum(g => g.Value)</div>
            </div>
        </div>
    </div>
    <div class="ui segment">
        <a asp-action="Edit" asp-route-id="@Model.Id" class="ui green button"><i class="write icon"></i>Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.Id" class="ui red button"><i class="delete icon"></i>Delete</a>
    </div>
</section>

<section class="ui two column grid">
    <div class="column">
        <div class="ui raised segment">
            <span class="ui yellow ribbon label"><i class="cubes icon"></i> Gold</span>
            <h2>Gold</h2>
        </div>
    </div>
    <div class="column">
        <div class="ui raised segment">
            <span class="ui purple right ribbon label"><i class="lab icon"></i> Experience</span>
            <h2>Experience</h2>
        </div>
    </div>
</section>

<div><a asp-action="Index">Back to List</a></div>

src/DnD/Views/Character/Edit.cshtml
@model DnD.Models.CharacterViewModels.CharacterViewModel

@{
    ViewData["Title"] = "Edit Character";
}

@await Html.PartialAsync("_Form", Model, new ViewDataDictionary(ViewData) { ["Button"] = "Edit", ["Icon"] = "write" })

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <environment names="Development">
        <script src="~/js/characterform.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/js/characterform.min.js" asp-append-version="true"></script>
    </environment>
}

src/DnD/Views/Character/Index.cshtml
@model IEnumerable<DnD.Models.Character>

@{
    ViewData["Title"] = "Characters";
}

<p><a asp-action="Create" class="ui green button"><i class="add icon"></i>Create Character</a></p>

<div class="ui cards">
@foreach(var item in Model)
{
    @await Html.PartialAsync("_CharacterCard", item)
}
</div>

src/DnD/Views/Character/_CharacterCard.cshtml
@model Character

<div class="ui card">
    @await Html.PartialAsync("_CharacterCardHeader")
    @if (!ViewData.ContainsKey("HideActions"))
    {
        <div class="extra content">
            <div class="ui two buttons">
                <a asp-action="Edit" asp-route-id="@Model.Id" class="ui green button"><i class="write icon"></i> Edit</a>
                <a asp-action="Delete" asp-route-id="@Model.Id" class="ui red button"><i class="delete icon"></i> Delete</a>
            </div>
        </div>
    }
</div>

src/DnD/Views/Character/_Form.cshtml
@model DnD.Models.CharacterViewModels.CharacterViewModel

<form asp-action="@ViewContext.RouteData.Values["action"]" class="ui form summary">
    @await Html.PartialAsync("_FormErrorSummary")
    <input asp-for="Id" />
    <div class="field">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="Name"></span>
        </div>
    </div>
    <div class="field">
        <label asp-for="Gender"></label>
        <div class="ui search selection dropdown allow-add">
            <input asp-for="Gender" />
            <i class="dropdown icon"></i>
            <div class="default text">Select a gender</div>
            <div class="menu">
                <div class="item" data-value="Male"><i class="@Html.GenderIcon("male") icon"></i> Male</div>
                <div class="item" data-value="Female"><i class="@Html.GenderIcon("female") icon"></i> Female</div>
                <div class="item" data-value="Agender"><i class="@Html.GenderIcon("agender") icon"></i> Agender</div>
                <div class="item" data-value="Other"><i class="@Html.GenderIcon("other") icon"></i> Other</div>
            </div>
        </div>
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="Gender"></span>
        </div>
    </div>
    <div class="field">
        <label asp-for="RaceId">Race (<a asp-action="Index" asp-controller="Info" @*Href is set by tag helpers*@ target="_blank"><i class="external icon"></i>Info</a>)</label>
        <select asp-for="RaceId" asp-items="ViewBag.RaceItems" class="ui selection dropdown create-default" id="race"></select>
    </div>
    <div class="field initial" data-tooltip="Initial Mana + Initial Life has to be equal to 15">
        <label asp-for="InitialLife"></label>
        <input asp-for="InitialLife" id="initial-life" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="InitialLife"></span>
        </div>
    </div>
    <div class="field initial" data-tooltip="Initial Mana + Initial Life has to be equal to 15">
        <label asp-for="InitialMana"></label>
        <input asp-for="InitialMana" id="initial-mana" />
        <div class="ui pointing red basic label error-label">
            <span asp-validation-for="InitialMana"></span>
        </div>
    </div>
    <button type="submit" class="ui green button"><i class="@ViewData["Icon"] icon"></i>@ViewData["Button"] </button>
    @if (Model != null && Model.Id.HasValue)
    {
        <a asp-action="Details" asp-route-id="@Model.Id" class="ui blue button"><i class="@Html.CharacterIcon() icon"></i>Character Details</a>
    }
</form>

<p><a asp-action="Index">Back to List</a></p>